# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiposDeServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('imagen', models.ImageField(upload_to='services')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('apellidos', models.CharField(max_length=1000)),
                ('aniosExperiencia', models.IntegerField()),
                ('telefono', models.CharField(max_length=1000)),
                ('correo', models.CharField(max_length=1000)),
                ('imagen', models.ImageField(upload_to='photos')),
                ('tiposDeServicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buscoayuda.TiposDeServicio')),
            ],
        ),
    ]
